export const ORDER_STATUS = '制单中,已受理,待派单,处理中,已取消,已关闭,无法处理'.split(',')
export const ORDER_SETTLE_STATUS = '未结算,结算中,已结算,免费'.split(',')
export const ORDER_QUOTE = '否,是,待定'.split(',')
export const ORDER_CHARGE = '否,是,待定'.split(',')
export const ORDER_OUT = '否,是,待定'.split(',')
export const ORDER_LEVEL = '请选择,A级,B级,C级,D级'.split(',')
export const ORDER_DEGREE = '请选择,非常紧急,紧急,一般'.split(',')
export const ORDER_SOURCE = '请选择,公司计划安排,PC WEB,微信,400客服电话,其他'.split(',')
export const ORDER_TYPE = '请选择,安装工单,保养工单,维修工单,投诉工单,巡检工单,移机调试,工艺调试,试焊申请,设备整改,培训工单'.split(',')
export const EDUCATION_LIST = '小学,初中,中专,高中,大专,本科,硕士,博士'.split(',')
export const STATUS_LIST = '离职,在职'.split(',')
export const SEX_LIST = '女,男'.split(',')

// 下一步
export const REPAIR_NEXT = '完工关闭,暂不关闭,内部派工,派给网点'.split(',')
// 处理进度
export const REPAIR_PROCESS = '请选择,故障检测中,配件维修中,等待配件更换,测试观察中,已处理完成,不能处理,其他'.split(',')
export const SERVICE_COMPLETE = '否,是'.split(',')
export const SERVICE_SETTLEMENT_METHOD = '免费,客付,厂付'.split(',')
export const SERVICE_HOTEL = '否,是'.split(',')
export const SERVICE_LAND_TRAFFIC = '否,是'.split(',')
export const SERVICE_AREA = '省内,省外,公司内,客户现场'.split(',')
export const CANCEL_REASON = '客户撤销,问题解决,其他'.split(',')
