<?php
/**
 * Created by PhpStorm.
 * User: natusi
 * Date: 2018-09-23
 * Time: 17:01
 */

return ['super_admin',
    'admin',
    'agent_add',
    'agent_list',
    'agent_view',
    'agent_edit',

    'staff_list',
    'staff_add',
    'staff_view',
    'staff_edit',

    'staff_docs',
    'staff_contact',

    'department_list',
    'department_add',
    'department_view',
    'department_edit',
    'signin_list',
    'signin_add',
    'signin_view',
    'signin_edit',
    'job_list',
    'job_add',
    'job_view',
    'job_edit',
    'post_list',
    'post_add',
    'post_view',
    'post_edit',

    'customer_list',
    'customer_add',
    'customer_edit',
    'customer_view',
    'customer_docs',
    'customer_contact',

    'quotation_list',
    'customercontact_list',
    'customercontact_add',
    'customercontact_view',
    'customercontact_edit',
    'customerquotation_list',
    'customerquotation_add',
    'customerquotation_view',
    'customerquotation_edit',
    'customerquotation_materiel_list',
    'customerquotation_materiel_add',
    'customerquotation_materiel_view',
    'customerquotation_materiel_edit',
    'customerequipment_list',
    'customerequipment_add',
    'customerequipment_view',
    'customerequipment_edit',
    'order_list',
    'order_service',
    'order_repair_list',
    'order_repair_add',
    'order_repair_view',
    'order_repair_edit',
    'order_install_list',
    'order_install_add',
    'order_install_view',
    'order_install_edit',
    'order_maintain_list',
    'order_maintain_add',
    'order_maintain_view',
    'order_maintain_edit',
    'order_confirm_list',
    'order_confirm_add',
    'order_confirm_view',
    'order_confirm_edit',
    'order_dispatch_list',
    'order_dispatch_add',
    'order_dispatch_view',
    'order_dispatch_edit',
    'order_dispose_list',
    'order_dispose_add',
    'order_dispose_view',
    'order_dispose_edit',
    'order_charge_list',
    'order_charge_add',
    'order_charge_view',
    'order_charge_edit',
    'order_close_list',
    'order_close_add',
    'order_close_view',
    'order_close_edit',
    'order_review_list',
    'order_review_add',
    'order_review_view',
    'order_review_edit',

    'order_flow',
    'order_flow_service',
    'order_flow_all_list',
    'order_flow_all_add',
    'order_flow_all_view',
    'order_flow_all_edit',
    'order_flow_repair_list',
    'order_flow_repair_add',
    'order_flow_repair_view',
    'order_flow_repair_edit',
    'order_flow_install_list',
    'order_flow_install_add',
    'order_flow_install_view',
    'order_flow_install_edit',
    'order_flow_maintain_list',
    'order_flow_maintain_add',
    'order_flow_maintain_view',
    'order_flow_maintain_edit',
    'order_flow_confirm_list',
    'order_flow_confirm_add',
    'order_flow_confirm_view',
    'order_flow_confirm_edit',
    'order_flow_dispatch_list',
    'order_flow_dispatch_add',
    'order_flow_dispatch_view',
    'order_flow_dispatch_edit',
    'order_flow_dispose_list',
    'order_flow_dispose_add',
    'order_flow_dispose_view',
    'order_flow_dispose_edit',
    'order_flow_charge_list',
    'order_flow_charge_add',
    'order_flow_charge_view',
    'order_flow_charge_edit',
    'order_flow_close_list',
    'order_flow_close_add',
    'order_flow_close_view',
    'order_flow_close_edit',
    'order_flow_review_list',
    'order_flow_review_add',
    'order_flow_review_view',
    'order_flow_review_edit',
    'order_flow_equipments_list',
    'order_flow_equipments_add',
    'order_flow_equipments_view',
    'order_flow_equipments_edit',
    'order_flow_equipments_remove',

    'knowledge_list',
    'knowledge_add',
    'knowledge_edit',
    'knowledge_view',
    'knowledge_remove',

    'machine_list',
    'machine_add',
    'machine_edit',
    'machine_view',
    'machine_price',
    'machine_customer',
    'machine_qrcode',
    'machine_stock',

    'machineqrcode_list',
    'machineqrcode_add',
    'machineqrcode_edit',
    'machineqrcode_view',

    'customer_equipment',
    'customer_equipment_list',
    'customer_equipment_add',
    'customer_equipment_view',
    'customer_equipment_edit',

    'kpm_list',
    'kpm_add',
    'kpm_view',
    'kpm_edit',

    'report_list',
    'report_view',

    'organization_list',
    'organization_add',
    'organization_view',
    'organization_edit',

    'base_service',
    'base_service_list',
    'base_service_add',
    'base_service_view',
    'base_service_edit',
];
