<?php
/**
 * Created by PhpStorm.
 * User: natusi
 * Date: 2018-09-23
 * Time: 17:01
 */

return ['super_admin',
    'admin',
    'agent_add',
    'agent_list',
    'agent_view',
    'agent_edit',

    'staff_list',
    'staff_add',
    'staff_view',
    'staff_edit',
    'department_list',
    'department_add',
    'department_view',
    'department_edit',
    'signin_list',
    'signin_add',
    'signin_view',
    'signin_edit',
    'job_list',
    'job_add',
    'job_view',
    'job_edit',
    'post_list',
    'post_add',
    'post_view',
    'post_edit',

    'customer_list',
    'customer_add',
    'customer_edit',
    'customer_docs',
    'customer_contact',
    'customercontact_list',
    'customercontact_add',
    'customercontact_view',
    'customercontact_edit',
    'order_list',
    'order_service',
    'order_repair_list',
    'order_repair_add',
    'order_repair_view',
    'order_repair_edit',
    'order_install_list',
    'order_install_add',
    'order_install_view',
    'order_install_edit',
    'order_maintain_list',
    'order_maintain_add',
    'order_maintain_view',
    'order_maintain_edit',
    'order_confirm_list',
    'order_confirm_add',
    'order_confirm_view',
    'order_confirm_edit',
    'order_dispatch_list',
    'order_dispatch_add',
    'order_dispatch_view',
    'order_dispatch_edit',
    'order_dispose_list',
    'order_dispose_add',
    'order_dispose_view',
    'order_dispose_edit',
    'order_charge_list',
    'order_charge_add',
    'order_charge_view',
    'order_charge_edit',
    'order_close_list',
    'order_close_add',
    'order_close_view',
    'order_close_edit',
    'order_review_list',
    'order_review_add',
    'order_review_view',
    'order_review_edit',

    'machine_list',
    'machine_add',
    'machine_edit',
    'machine_price',
    'machine_customer',
    'machine_qrcode',
    'machine_stock',

    'staff_list',
    'staff_docs',
    'staff_contact',

    'organization_list',
    'organization_add',
    'organization_view',
    'organization_edit',
];
